---
name: 'Lint'
on:
  - 'pull_request'
  - 'push'
jobs:
  eclint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'snow-actions/eclint@v1.0.1'
  shellcheck:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'

      # TODO: Lint `*.bats`
      - uses: 'ludeeus/action-shellcheck@0.5.0'
  yamllint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'ibiqlik/action-yamllint@v1'
        with:
          file_or_dir: 'test/'
